// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4cMj6pZZqb4ERyrZj6e6Nomyl0JcbfG8',
    appId: '1:360494384501:web:005c772b04bad93a447f3c',
    messagingSenderId: '360494384501',
    projectId: 'aiish-ea208',
    authDomain: 'aiish-ea208.firebaseapp.com',
    storageBucket: 'aiish-ea208.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRe2Nr-hHk3PKzNWf8b5tuYM81MhsAMHk',
    appId: '1:360494384501:android:189151d078630aaf447f3c',
    messagingSenderId: '360494384501',
    projectId: 'aiish-ea208',
    storageBucket: 'aiish-ea208.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4cMj6pZZqb4ERyrZj6e6Nomyl0JcbfG8',
    appId: '1:360494384501:web:24ef6cc15368b8c4447f3c',
    messagingSenderId: '360494384501',
    projectId: 'aiish-ea208',
    authDomain: 'aiish-ea208.firebaseapp.com',
    storageBucket: 'aiish-ea208.firebasestorage.app',
  );
}
