// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANg31BgY0FqK-SAMxtBacAQ1vuliqSx-k',
    appId: '1:63857421124:web:421b069afa8ff328eb8511',
    messagingSenderId: '63857421124',
    projectId: 'soundify-2026',
    authDomain: 'soundify-2026.firebaseapp.com',
    storageBucket: 'soundify-2026.firebasestorage.app',
    measurementId: 'G-Z167DZKZJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy4FGIjuPphX5ZhYY5qqyjD7opH82PwW8',
    appId: '1:63857421124:android:c065104e0c5634f0eb8511',
    messagingSenderId: '63857421124',
    projectId: 'soundify-2026',
    storageBucket: 'soundify-2026.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANg31BgY0FqK-SAMxtBacAQ1vuliqSx-k',
    appId: '1:63857421124:web:261787dac748e160eb8511',
    messagingSenderId: '63857421124',
    projectId: 'soundify-2026',
    authDomain: 'soundify-2026.firebaseapp.com',
    storageBucket: 'soundify-2026.firebasestorage.app',
    measurementId: 'G-N8CBFR2GX0',
  );
}
